### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by alanshaw** [tableflip/tune#31]
Seeing a lot of these in the live logs:

```
Exception in callback of async function: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at imports/api/github/methods.js:53:20
    at /home/tune/tune/bundle/programs/server/npm/node_modules/async/lib/async.js:52:16
    at /home/tune/tune/bundle/programs/server/npm/node_modules/async/lib/async.js:1209:30
    at imports/api/github/methods.js:45:9
    at imports/lib/github/github-interface.js:125:21
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by richsilv** [comment]
This is because in the event of a missing `schema.json` file, we were using the string `"{}"` instead.  However, we're now Base64 decoding it before trying to parse, which `JSON.parse` isn't going to like much...
